### ISSUE TITLE
Generic Observer pattern

### ISSUE THREAD

**Issue by ismtabo** [iot-mixin/temp-humd-monitor-arduino-mqtt#3]
Proposal of Observer pattern:
![alt-image](https://www.planttext.com/api/plantuml/png/POz13e8m44NtFSKFRa23YLj2t7W05fwWbAdKaDQqWubHxouGYX6xclpyUNsZEXa2pdrz9SLu2Wnl1yaiLPjMKvhDOKD_uGRzhP5CQIRUmbWchwKYLByqwzZenwfpSbPvOefTpENGrq5vKrCwIurhOa0GEj8CfwEjQ4Wl_nV3kdOUiklWO2nS7SZVoOTY0hlzOa6s6PL8Y7XsSaYGUtDfEKUoJQ9_yONWAEQmVENvIdxXHCRgjWBbUDOqVm00)

(edit link to uml: [source](https://www.planttext.com/?text=POz13e8m44NtFSKFRa23YLj2t7W05fwWbAdKaDQqWubHxouGYX6xclpyUNsZEXa2pdrz9SLu2Wnl1yaiLPjMKvhDOKD_uGRzhP5CQIRUmbWchwKYLByqwzZenwfpSbPvOefTpENGrq5vKrCwIurhOa0GEj8CfwEjQ4Wl_nV3kdOUiklWO2nS7SZVoOTY0hlzOa6s6PL8Y7XsSaYGUtDfEKUoJQ9_yONWAEQmVENvIdxXHCRgjWBbUDOqVm00))

**Comment by Canario0** [comment]
U have to add a class "ConcreteSubject" with the generic get and set for the subject value, like this one: https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/EstructuraPatronObservador.png/600px-EstructuraPatronObservador.png

**Comment by ismtabo** [comment]
I don't think so, as concrete subject only add state member with type. And that is what we want to avoid. So that class won't give extra information, and inheritance have no sense.

That "ConcreteSubject", on my opinion, should be the implementation we want to add.

Other solution could be create a generic class of State. With a `value` member and getters and setters. And "ConcreteSubject" can have a state member of that class. Later, I can draw a class diagram.
